### ISSUE TITLE
BOOM

### ISSUE THREAD

**Issue by AFUDIrk** [je1rav/UV-K5_upconverter#1]
Hello, I had circuit boards made for the projects. Unfortunately, I saw too late that not all of the component values ​​were given in the circuit diagrams. Can you please send me these for all of the circuit boards (MLA, bar antenna, upconverter, LNA) or add them to your repository?
73 de DK4DO Dirk

**Comment by AFUDIrk** [comment]
Hello, I had circuit boards made for the projects. Unfortunately, I saw too late that not all of the component values ​​were given in the circuit diagrams. Can you please send me these for all of the circuit boards (MLA, bar antenna, upconverter, LNA) or add them to your repository?
73 de DK4DO Dirk

**Comment by je1rav** [comment]
Dear Dirk,

The values of most parts can be found in the circuit diagrams.
Also, the parts list can be found in the documentation (unfortunately the
documentation is written in Japanese).
Could you use a language translator such as deelp?

If you ask me  the individual parts, I can help you.

Best regards,
Hitoshi, JE1RAV

2024年7月3日(水) 22:27 Dirk ***@***.***>:

**Comment by AFUDIrk** [comment]
Hello dear friend,
thank you for your email.
I have now translated the entire page step by step, as Google could not
translate the entire page at once.
Unfortunately, I have only just seen that the components are named in the
Japanese text.
Thank you very much
Dirk, DK4DO

Am Do., 4. Juli 2024 um 14:24 Uhr schrieb je1rav ***@***.***>:
